filter:
    excluded_paths: [vendor/*, tests/*, examples/*, assets/*, src/statemachine/utils/PlantUML.php]
before_commands:
    - 'composer install --dev --prefer-source'
tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests, examples, asssets]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests, examples, assets]
