language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - 5.6
install:
  - composer --no-interaction install

before_script:
  - composer selfupdate
  - composer update --prefer-source --no-interaction 
  - sudo apt-get update -qq
  - sudo apt-get install -y php5-redis
  
script: phpunit --configuration tests/phpunit-travis.xml --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
